[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
launchpad_factory = "5gijUGHyDFRn92iDFraCFN8g3LfwHTSKR3ftapJvYrkJ"
token_launchpad = "JATxSqCECNZZU94ZKmFzF3FcSP1kg6JmDr9cxQ9J1Q84"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/abdec2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
