[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
launchpad_factory = "3EWEm3bTAdMPawiD1pAzRyXRsMjYJbwhHSiRWy7VimMx"
token_launchpad = "BYRLxSc7PRKLvM4MR9EGQRFG5PYA9UiFKQdfscSm4xSH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/abdec2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
