[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
launchpad_factory = "AGjcCEgWozAyFxFUjjPudiGq77BuKvygXHX9mR7ssqDx"
token_launchpad = "5xdEgYSLUqzPBGxK2yPoQvbnEuah6iiYMGwhTLJNkXhA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/abdec2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
